[FILES]
DOC=C:\Projects\Delphi\ITAPT_ISTRA\IMP_FILE\IMP_Controller\Data\#_DOC.CSV
DOCITEM=C:\Projects\Delphi\ITAPT_ISTRA\IMP_FILE\IMP_Controller\Data\#_DOCITEM.CSV
DOCPAY=C:\Projects\Delphi\ITAPT_ISTRA\IMP_FILE\IMP_Controller\Data\#_DOCPAY.CSV
DOCOFF=C:\Projects\Delphi\ITAPT_ISTRA\IMP_FILE\IMP_Controller\Data\#_DOCOFF.CSV
[DEPENDENCIES]
DOC=DOCITEM,DOCPAY
[FILE]
ANSWER=C:\Projects\Delphi\ITAPT_ISTRA\IMP_FILE\IMP_Controller\Data\Answer\

#IMP_SAVE_PATH=E:\ITWH\EXCHANGE\PARUS\Save\
#IMP_SAVE_PATH=C:\Projects\Delphi\ITAPT_ISTRA\IMP_FILE\IMP_Controller\Data\Backup\
IMP_SAVE_REGIME=ALL

IMP_BUF_SIZE=2
IMP_DLM=|
#IMP_FILE_CODING=UTF8
IMP_FILE_MOVE_TMP=C:\Projects\Delphi\ITAPT_ISTRA\IMP_FILE\IMP_Controller\Data\TMP\
IMP_FILE_MOVE_ATT=10
IMP_FILE_MOVE_SLEEP=30
IMP_FILE_MOVE_TIME=900

EXP_FILE_PATH=E:\ITWH\EXCHANGE\ITWH-PARUS\
EXP_TMP=E:\ITWH\EXCHANGE\PARUS\BIN\TMP\
#EXP_END_FILE=E:\ITWH\EXCHANGE\PARUS-ITWH\END_PARUS_EXP
#WAIT_INTERVAL=1000
#WAIT_HOUR=0
#WAIT_MIN=1
[DB]

DB_NAME=PARUS
USER=PARUS
PSW=827B49611E7EB4AE3029A9B39309C953F21B48722CD542CD6C85CD14C505

COMMAND_VIEW=V_UDO_COMMAND
COMMAND_PROC=P_UDO_COMMAND_RUN

EXP_PREP_PROC=P_UDO_ITAPT_BUFF_PREP
EXP_LOAD_VIEW=V_ITAPT_BUF_FILE
EXP_CLEAR_PROC=P_UDO_ITAPT_BUFF_CLEAR

IMP_SAVE_PROC=P_UDO_CRECHECK_ITAPT_IMPORT_B

CHECK_INTERVAL=5
[OTHERS]
IMP_MUTEX=X1
PERIOD=16H
REGIME=0
LOG=C:\Projects\Delphi\ITAPT_ISTRA\IMP_FILE\IMP_Controller\Data\Log\
IMP_PROG=ORAIMP.EXE
COMMAND_LOG=EXCHANGE.LOG
EXP_LOG=EXPORT.LOG
IMP_LOG=IMPORT.LOG
[SHEDULER]
IMP_BGN=08:00
IMP_END=23:59
IMP_INT=10
