[FILES]
DOC=C:\Project\Delphi\ITAPT\IMP_Controller\Data\#_DOC.CSV;P_UDO_ITAPT_CRECHEC_IMP(ID,CASHIER,DOCTOR_ID,DOCDATE,CHECKTYPE,NOTE,FNNUMB,CREREGNUMB,FISCALDOCNUMB,RCPSR,RCPNUMB,RCPDATE)
DOCITEM=C:\Project\Delphi\ITAPT\IMP_Controller\Data\#_DOCITEM.CSV;P_UDO_ITAPT_CRECHEC_SP_IMP(ID,PID,NOMEN_ID,LOTID,QUANTITY,FREETAX,INCLTAX,PRICE,NUMB,NOTE,SUMWTAX,SUMWOTAX,SUMTAX,TAXRATE,MARK_CODE)
DOCPAY=C:\Project\Delphi\ITAPT\IMP_Controller\Data\#_DOCPAY.CSV;P_UDO_ITAPT_CRECHEC_PAY_IMP(ID,PID,PAYSUM,PAYTYPE)
[FILE]
ANSWER=E:\ITWH\EXCHANGE\PARUS\BIN\TMP\Answer.prm

#IMP_SAVE_PATH=E:\ITWH\EXCHANGE\PARUS\Save\
IMP_SAVE_PATH=C:\Project\Delphi\ITAPT\IMP_Controller\Data\Bacup\
IMP_SAVE_REGIME=ALL

IMP_BUF_SIZE=2
IMP_DLM=|
#IMP_FILE_CODING=UTF8
IMP_FILE_MOVE_TMP=C:\Project\Delphi\ITAPT\IMP_Controller\Data\TMP\
IMP_FILE_MOVE_ATT=10
IMP_FILE_MOVE_SLEEP=30
IMP_FILE_MOVE_TIME=900

EXP_FILE_PATH=E:\ITWH\EXCHANGE\ITWH-PARUS\
EXP_TMP=E:\ITWH\EXCHANGE\PARUS\BIN\TMP\
#EXP_END_FILE=E:\ITWH\EXCHANGE\PARUS-ITWH\END_PARUS_EXP
#WAIT_INTERVAL=1000
#WAIT_HOUR=0
#WAIT_MIN=1
[DB]

DB_NAME=PARUS
USER=PARUS
PSW=8F3EFD489CE449F6CD1FCF3DADFF6FDD8DDF0C0BFC93CFB95D33EF99BDD3

COMMAND_VIEW=V_UDO_COMMAND
COMMAND_PROC=P_UDO_COMMAND_RUN

EXP_PREP_PROC=P_UDO_ITAPT_BUFF_PREP
EXP_LOAD_VIEW=V_ITAPT_BUF_FILE
EXP_CLEAR_PROC=P_UDO_ITAPT_BUFF_CLEAR

IMP_SAVE_PROC=P_UDO_CRECHECK_ITAPT_IMPORT_B

CHECK_INTERVAL=5
[OTHERS]
PERIOD=16H
REGIME=0
LOG=C:\Project\Delphi\ITAPT\IMP_Controller\Log\
IMP_PROG:=ORAIMP.EXE
COMMAND_LOG=EXCHANGE.LOG
EXP_LOG=EXPORT.LOG
IMP_LOG=IMPORT.LOG
[SHEDULER]
IMP_BGN=08:00
IMP_END=23:59
IMP_INT=10